disabled = false
languageCode = "en-US"
languageName = "English"
weight = 1
title = "Pixel Patchwork"
subtitle = 'belgian gamedev minorities'

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[permalinks]
posts = "/:section/:slug/"
